#!/usr/sbin/env python3
https://yiyibooks.cn/xx/python_352/library/index.html
type    str     list    tuple   dict    set     range(n)    enumerate(seq)
seq     1       1       1       1       1       range(0,n)  <ob at 0x>
seq[i]  1       1       1       2       0       1           0
seq[::] 1       1       1       0       0       1           0
for i   1       1       1       key     1       1           (idx,val) i=(idx,val) idx,val (ind,val)
[](){}  1       1       1       key     1       1           (idx,val) 
.index  1       1       1       0       0       1           0
.count  1       1       1       0       0       1           0
len()   1       1       1       1       1       1           0
enumerate 1     1       1       key     1       1           (idx,(idx,val))
str     -       '[]'    '()'    '{}'    '{}'   'range(0,n)' '<ob at 0x>'
dict    (zip(any,any))          (enumerate(seq))
解析    0       1       1       1       1       0           0



str
str(123)
'abc'.capitalize()
'abcDEF'.upper()
'abcDEF'.lower()
' \tabc\n'.strip()             ##blank not only blankspace
' \tabc\n'.lstrip()
' \tabc\n'.rstrip()
'1212'.replace("1","2")
'hello world'.center(50,"*")   ##argv[1] default " "
'hello world'.ljust(50,"*")
'hello world'.rjust(50,"*")
'1as'.isidentifier()           ##no keyword.iskeyword(k) function
'hao'.isalpha()
'123'.isdigit()
'abc123'.isalnum()
'192.168.1.11'.split('.',2)    ##default blank,return list type      [0,2]!!!
'123123123'.endswith('12',0,5)
'abc1!'.islower()              ##0 upper,1+ lower
'ABC1!'.islower()              ##0 lower,1+ upper
'123123'.index('23')
'121212'.count('1',0,1)        ##[0,1)
list
.remove('first')
.append('end')  ##end is a element
.expend('abc')  ##abc is a seq(string)
.sort()
.reverse()
.pop(-1)        ##return values,default index=-1
.index("bob")   ##return the index of the first "bob"
.count('1')
.insert(0, x)   ##a=[0,1];a.insert(100,-1)
.sort()         ##sort source list,no return
.clear()        ##del a[:]
del a           ##a;nameerror
tuple
.index('bob')
.count('bob')
type((1))       ##!!!!return int!!!!(1,)


