#!/bin/bash
read -p "是否添加网卡$1:" a
if [ "$a" = n ];then echo 不添加网卡;else nmcli connection add type ethernet ifname $1 con-name $1;fi
path='/etc/sysconfig/network-scripts/ifcfg-'$1
sed -i 's/BOOTPROTO.*/BOOTPROTO=none/' $path
sed -i 's/ONBOOT.*/ONBOOT=yes/' $path
grep -q IPADDR $path;
if (($?==0));then	sed -i "s/IPADDR.*/IPADDR=$2/" $path
	     else	echo "IPADDR=$2" >> $path		;fi
grep -q PREFIX $path;
if (($?==0));then	sed -i "s/PREFIX.*/PREFIX=24/" $path
	     else	echo "PREFIX=24" >> $path		;fi
service network restart
